#define PIN_SCR_LED GPIOA, GPIO_PIN_3
#define PIN_BUT1 GPIOC, GPIO_PIN_15
#define PIN_BUT2 GPIOC, GPIO_PIN_14
#define PIN_BUT3 GPIOA, GPIO_PIN_0
#define PIN_BUT4 GPIOC, GPIO_PIN_13
#define PIN_BUT5 GPIOA, GPIO_PIN_1
#define PIN_BUT6 GPIOA, GPIO_PIN_6
