#define COL_BG_STATUSBAR		DARKGREY
#define COL_BG_PAGE 			LIGHTGREY
#define COL_BG_HELPER 			YELLOW
#define COL_BG_DATA_BIG			BLACK
#define COL_BG_DATA_SMALL		LIGHTGREY
#define COL_TXT_STATUSBAR 		WHITE
#define COL_TXT_MENUBAR 		BLACK
#define COL_TXT_PAGE 			BLACK
#define COL_TXT_HELPER 			BLACK
#define COL_TXT_SELECT 			RED
#define COL_TXT_DATA 			BLACK
#define COL_DATA_LINES 			BLACK
#define COL_MENU_LINES 			BLACK
#define COL_BG_PAGE_SELECT 		YELLOW
#define COL_TXT_MENUBAR_SELECT 	BLACK
#define COL_TXT_DATA_BIG		YELLOW
#define COL_TXT_DATA_SMALL		BLACK

#define FONT_STATUSBAR			FONT2
#define FONT_PAGE				FONT3
#define FONT_HELPER				FONT3
#define FONT_MENU				FONT2
#define FONT_DATA_SMALL			FONT2
#define FONT_DATA_BIG			FONT4

#define PARAM_WIDTH_STATUSBAR 	14
#define PARAM_WIDTH_MENUBAR 	20
#define PARAM_DELAY_KEYS 		125
#define PARAM_DATA_BLOCK_COUNT	8
#define PARAM_DATA_BLOCK_SIZE	80
#define PARAM_PAGE_COUNT		4

#define POS_HELPER_B1 			1, 200
#define POS_HELPER_B2 			1, 220
#define POS_HELPER_B3 			140, 200
#define POS_HELPER_B4 			140, 220
#define POS_HELPER_B5 			240, 200
#define POS_HELPER_B6 			240, 220
